// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package provisionmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProvisioner creates a new instance of MockProvisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvisioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvisioner {
	mock := &MockProvisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvisioner is an autogenerated mock type for the Provisioner type
type MockProvisioner struct {
	mock.Mock
}

type MockProvisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvisioner) EXPECT() *MockProvisioner_Expecter {
	return &MockProvisioner_Expecter{mock: &_m.Mock}
}

// Provision provides a mock function for the type MockProvisioner
func (_mock *MockProvisioner) Provision(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Provision")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvisioner_Provision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provision'
type MockProvisioner_Provision_Call struct {
	*mock.Call
}

// Provision is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvisioner_Expecter) Provision(ctx interface{}) *MockProvisioner_Provision_Call {
	return &MockProvisioner_Provision_Call{Call: _e.mock.On("Provision", ctx)}
}

func (_c *MockProvisioner_Provision_Call) Run(run func(ctx context.Context)) *MockProvisioner_Provision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvisioner_Provision_Call) Return(err error) *MockProvisioner_Provision_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvisioner_Provision_Call) RunAndReturn(run func(ctx context.Context) error) *MockProvisioner_Provision_Call {
	_c.Call.Return(run)
	return _c
}
