// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package provisionmock

import (
	"context"

	"github.com/slok/sbx/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSandboxAccessor creates a new instance of MockSandboxAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSandboxAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSandboxAccessor {
	mock := &MockSandboxAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSandboxAccessor is an autogenerated mock type for the SandboxAccessor type
type MockSandboxAccessor struct {
	mock.Mock
}

type MockSandboxAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSandboxAccessor) EXPECT() *MockSandboxAccessor_Expecter {
	return &MockSandboxAccessor_Expecter{mock: &_m.Mock}
}

// CopyTo provides a mock function for the type MockSandboxAccessor
func (_mock *MockSandboxAccessor) CopyTo(ctx context.Context, srcLocal string, dstRemote string) error {
	ret := _mock.Called(ctx, srcLocal, dstRemote)

	if len(ret) == 0 {
		panic("no return value specified for CopyTo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, srcLocal, dstRemote)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSandboxAccessor_CopyTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyTo'
type MockSandboxAccessor_CopyTo_Call struct {
	*mock.Call
}

// CopyTo is a helper method to define mock.On call
//   - ctx context.Context
//   - srcLocal string
//   - dstRemote string
func (_e *MockSandboxAccessor_Expecter) CopyTo(ctx interface{}, srcLocal interface{}, dstRemote interface{}) *MockSandboxAccessor_CopyTo_Call {
	return &MockSandboxAccessor_CopyTo_Call{Call: _e.mock.On("CopyTo", ctx, srcLocal, dstRemote)}
}

func (_c *MockSandboxAccessor_CopyTo_Call) Run(run func(ctx context.Context, srcLocal string, dstRemote string)) *MockSandboxAccessor_CopyTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSandboxAccessor_CopyTo_Call) Return(err error) *MockSandboxAccessor_CopyTo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSandboxAccessor_CopyTo_Call) RunAndReturn(run func(ctx context.Context, srcLocal string, dstRemote string) error) *MockSandboxAccessor_CopyTo_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockSandboxAccessor
func (_mock *MockSandboxAccessor) Exec(ctx context.Context, command []string, opts model.ExecOpts) (*model.ExecResult, error) {
	ret := _mock.Called(ctx, command, opts)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *model.ExecResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, model.ExecOpts) (*model.ExecResult, error)); ok {
		return returnFunc(ctx, command, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, model.ExecOpts) *model.ExecResult); ok {
		r0 = returnFunc(ctx, command, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExecResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, model.ExecOpts) error); ok {
		r1 = returnFunc(ctx, command, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSandboxAccessor_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockSandboxAccessor_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - command []string
//   - opts model.ExecOpts
func (_e *MockSandboxAccessor_Expecter) Exec(ctx interface{}, command interface{}, opts interface{}) *MockSandboxAccessor_Exec_Call {
	return &MockSandboxAccessor_Exec_Call{Call: _e.mock.On("Exec", ctx, command, opts)}
}

func (_c *MockSandboxAccessor_Exec_Call) Run(run func(ctx context.Context, command []string, opts model.ExecOpts)) *MockSandboxAccessor_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 model.ExecOpts
		if args[2] != nil {
			arg2 = args[2].(model.ExecOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSandboxAccessor_Exec_Call) Return(execResult *model.ExecResult, err error) *MockSandboxAccessor_Exec_Call {
	_c.Call.Return(execResult, err)
	return _c
}

func (_c *MockSandboxAccessor_Exec_Call) RunAndReturn(run func(ctx context.Context, command []string, opts model.ExecOpts) (*model.ExecResult, error)) *MockSandboxAccessor_Exec_Call {
	_c.Call.Return(run)
	return _c
}
