dir: '{{.InterfaceDir}}/{{.SrcPackageName}}mock'
filename: mocks.go
force-file-write: true
structname: 'Mock{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}mock'
template: testify
packages:
  github.com/slok/sbx/internal/sandbox:
    interfaces:
      Engine:
  github.com/slok/sbx/internal/provision:
    interfaces:
      Provisioner:
        config:
          filename: mock_provisioner.go
      SandboxAccessor:
        config:
          filename: mock_sandbox_accessor.go
  github.com/slok/sbx/internal/storage:
    interfaces:
      Repository:
  github.com/slok/sbx/internal/image:
    interfaces:
      ImageManager:
      SnapshotManager:
