// Code generated by mockery v2.53.5. DO NOT EDIT.

package enginemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/slok/sbx/internal/model"
)

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine struct {
	mock.Mock
}

type MockEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEngine) EXPECT() *MockEngine_Expecter {
	return &MockEngine_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cfg
func (_m *MockEngine) Create(ctx context.Context, cfg model.SandboxConfig) (*model.Sandbox, error) {
	ret := _m.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Sandbox
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SandboxConfig) (*model.Sandbox, error)); ok {
		return rf(ctx, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.SandboxConfig) *model.Sandbox); ok {
		r0 = rf(ctx, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sandbox)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.SandboxConfig) error); ok {
		r1 = rf(ctx, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEngine_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEngine_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg model.SandboxConfig
func (_e *MockEngine_Expecter) Create(ctx interface{}, cfg interface{}) *MockEngine_Create_Call {
	return &MockEngine_Create_Call{Call: _e.mock.On("Create", ctx, cfg)}
}

func (_c *MockEngine_Create_Call) Run(run func(ctx context.Context, cfg model.SandboxConfig)) *MockEngine_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SandboxConfig))
	})
	return _c
}

func (_c *MockEngine_Create_Call) Return(_a0 *model.Sandbox, _a1 error) *MockEngine_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEngine_Create_Call) RunAndReturn(run func(context.Context, model.SandboxConfig) (*model.Sandbox, error)) *MockEngine_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, id
func (_m *MockEngine) Remove(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEngine_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockEngine_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEngine_Expecter) Remove(ctx interface{}, id interface{}) *MockEngine_Remove_Call {
	return &MockEngine_Remove_Call{Call: _e.mock.On("Remove", ctx, id)}
}

func (_c *MockEngine_Remove_Call) Run(run func(ctx context.Context, id string)) *MockEngine_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEngine_Remove_Call) Return(_a0 error) *MockEngine_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_Remove_Call) RunAndReturn(run func(context.Context, string) error) *MockEngine_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, id
func (_m *MockEngine) Start(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEngine_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockEngine_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEngine_Expecter) Start(ctx interface{}, id interface{}) *MockEngine_Start_Call {
	return &MockEngine_Start_Call{Call: _e.mock.On("Start", ctx, id)}
}

func (_c *MockEngine_Start_Call) Run(run func(ctx context.Context, id string)) *MockEngine_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEngine_Start_Call) Return(_a0 error) *MockEngine_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_Start_Call) RunAndReturn(run func(context.Context, string) error) *MockEngine_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with given fields: ctx, id
func (_m *MockEngine) Status(ctx context.Context, id string) (*model.Sandbox, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *model.Sandbox
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Sandbox, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Sandbox); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sandbox)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEngine_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockEngine_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEngine_Expecter) Status(ctx interface{}, id interface{}) *MockEngine_Status_Call {
	return &MockEngine_Status_Call{Call: _e.mock.On("Status", ctx, id)}
}

func (_c *MockEngine_Status_Call) Run(run func(ctx context.Context, id string)) *MockEngine_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEngine_Status_Call) Return(_a0 *model.Sandbox, _a1 error) *MockEngine_Status_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEngine_Status_Call) RunAndReturn(run func(context.Context, string) (*model.Sandbox, error)) *MockEngine_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: ctx, id
func (_m *MockEngine) Stop(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEngine_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockEngine_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEngine_Expecter) Stop(ctx interface{}, id interface{}) *MockEngine_Stop_Call {
	return &MockEngine_Stop_Call{Call: _e.mock.On("Stop", ctx, id)}
}

func (_c *MockEngine_Stop_Call) Run(run func(ctx context.Context, id string)) *MockEngine_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEngine_Stop_Call) Return(_a0 error) *MockEngine_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_Stop_Call) RunAndReturn(run func(context.Context, string) error) *MockEngine_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEngine creates a new instance of MockEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEngine {
	mock := &MockEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
