// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sandboxmock

import (
	"context"

	"github.com/slok/sbx/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEngine creates a new instance of MockEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEngine {
	mock := &MockEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine struct {
	mock.Mock
}

type MockEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEngine) EXPECT() *MockEngine_Expecter {
	return &MockEngine_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockEngine
func (_mock *MockEngine) Check(ctx context.Context) []model.CheckResult {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 []model.CheckResult
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.CheckResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CheckResult)
		}
	}
	return r0
}

// MockEngine_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockEngine_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEngine_Expecter) Check(ctx interface{}) *MockEngine_Check_Call {
	return &MockEngine_Check_Call{Call: _e.mock.On("Check", ctx)}
}

func (_c *MockEngine_Check_Call) Run(run func(ctx context.Context)) *MockEngine_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEngine_Check_Call) Return(checkResults []model.CheckResult) *MockEngine_Check_Call {
	_c.Call.Return(checkResults)
	return _c
}

func (_c *MockEngine_Check_Call) RunAndReturn(run func(ctx context.Context) []model.CheckResult) *MockEngine_Check_Call {
	_c.Call.Return(run)
	return _c
}

// CopyFrom provides a mock function for the type MockEngine
func (_mock *MockEngine) CopyFrom(ctx context.Context, id string, srcRemote string, dstLocal string) error {
	ret := _mock.Called(ctx, id, srcRemote, dstLocal)

	if len(ret) == 0 {
		panic("no return value specified for CopyFrom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, srcRemote, dstLocal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEngine_CopyFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyFrom'
type MockEngine_CopyFrom_Call struct {
	*mock.Call
}

// CopyFrom is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - srcRemote string
//   - dstLocal string
func (_e *MockEngine_Expecter) CopyFrom(ctx interface{}, id interface{}, srcRemote interface{}, dstLocal interface{}) *MockEngine_CopyFrom_Call {
	return &MockEngine_CopyFrom_Call{Call: _e.mock.On("CopyFrom", ctx, id, srcRemote, dstLocal)}
}

func (_c *MockEngine_CopyFrom_Call) Run(run func(ctx context.Context, id string, srcRemote string, dstLocal string)) *MockEngine_CopyFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEngine_CopyFrom_Call) Return(err error) *MockEngine_CopyFrom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEngine_CopyFrom_Call) RunAndReturn(run func(ctx context.Context, id string, srcRemote string, dstLocal string) error) *MockEngine_CopyFrom_Call {
	_c.Call.Return(run)
	return _c
}

// CopyTo provides a mock function for the type MockEngine
func (_mock *MockEngine) CopyTo(ctx context.Context, id string, srcLocal string, dstRemote string) error {
	ret := _mock.Called(ctx, id, srcLocal, dstRemote)

	if len(ret) == 0 {
		panic("no return value specified for CopyTo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, srcLocal, dstRemote)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEngine_CopyTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyTo'
type MockEngine_CopyTo_Call struct {
	*mock.Call
}

// CopyTo is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - srcLocal string
//   - dstRemote string
func (_e *MockEngine_Expecter) CopyTo(ctx interface{}, id interface{}, srcLocal interface{}, dstRemote interface{}) *MockEngine_CopyTo_Call {
	return &MockEngine_CopyTo_Call{Call: _e.mock.On("CopyTo", ctx, id, srcLocal, dstRemote)}
}

func (_c *MockEngine_CopyTo_Call) Run(run func(ctx context.Context, id string, srcLocal string, dstRemote string)) *MockEngine_CopyTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEngine_CopyTo_Call) Return(err error) *MockEngine_CopyTo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEngine_CopyTo_Call) RunAndReturn(run func(ctx context.Context, id string, srcLocal string, dstRemote string) error) *MockEngine_CopyTo_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockEngine
func (_mock *MockEngine) Create(ctx context.Context, cfg model.SandboxConfig) (*model.Sandbox, error) {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.SandboxConfig) (*model.Sandbox, error)); ok {
		return returnFunc(ctx, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.SandboxConfig) *model.Sandbox); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sandbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.SandboxConfig) error); ok {
		r1 = returnFunc(ctx, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEngine_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEngine_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg model.SandboxConfig
func (_e *MockEngine_Expecter) Create(ctx interface{}, cfg interface{}) *MockEngine_Create_Call {
	return &MockEngine_Create_Call{Call: _e.mock.On("Create", ctx, cfg)}
}

func (_c *MockEngine_Create_Call) Run(run func(ctx context.Context, cfg model.SandboxConfig)) *MockEngine_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.SandboxConfig
		if args[1] != nil {
			arg1 = args[1].(model.SandboxConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEngine_Create_Call) Return(sandbox *model.Sandbox, err error) *MockEngine_Create_Call {
	_c.Call.Return(sandbox, err)
	return _c
}

func (_c *MockEngine_Create_Call) RunAndReturn(run func(ctx context.Context, cfg model.SandboxConfig) (*model.Sandbox, error)) *MockEngine_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockEngine
func (_mock *MockEngine) Exec(ctx context.Context, id string, command []string, opts model.ExecOpts) (*model.ExecResult, error) {
	ret := _mock.Called(ctx, id, command, opts)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *model.ExecResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, model.ExecOpts) (*model.ExecResult, error)); ok {
		return returnFunc(ctx, id, command, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, model.ExecOpts) *model.ExecResult); ok {
		r0 = returnFunc(ctx, id, command, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExecResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string, model.ExecOpts) error); ok {
		r1 = returnFunc(ctx, id, command, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEngine_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockEngine_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - command []string
//   - opts model.ExecOpts
func (_e *MockEngine_Expecter) Exec(ctx interface{}, id interface{}, command interface{}, opts interface{}) *MockEngine_Exec_Call {
	return &MockEngine_Exec_Call{Call: _e.mock.On("Exec", ctx, id, command, opts)}
}

func (_c *MockEngine_Exec_Call) Run(run func(ctx context.Context, id string, command []string, opts model.ExecOpts)) *MockEngine_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 model.ExecOpts
		if args[3] != nil {
			arg3 = args[3].(model.ExecOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEngine_Exec_Call) Return(execResult *model.ExecResult, err error) *MockEngine_Exec_Call {
	_c.Call.Return(execResult, err)
	return _c
}

func (_c *MockEngine_Exec_Call) RunAndReturn(run func(ctx context.Context, id string, command []string, opts model.ExecOpts) (*model.ExecResult, error)) *MockEngine_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Forward provides a mock function for the type MockEngine
func (_mock *MockEngine) Forward(ctx context.Context, id string, ports []model.PortMapping) error {
	ret := _mock.Called(ctx, id, ports)

	if len(ret) == 0 {
		panic("no return value specified for Forward")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []model.PortMapping) error); ok {
		r0 = returnFunc(ctx, id, ports)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEngine_Forward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forward'
type MockEngine_Forward_Call struct {
	*mock.Call
}

// Forward is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ports []model.PortMapping
func (_e *MockEngine_Expecter) Forward(ctx interface{}, id interface{}, ports interface{}) *MockEngine_Forward_Call {
	return &MockEngine_Forward_Call{Call: _e.mock.On("Forward", ctx, id, ports)}
}

func (_c *MockEngine_Forward_Call) Run(run func(ctx context.Context, id string, ports []model.PortMapping)) *MockEngine_Forward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []model.PortMapping
		if args[2] != nil {
			arg2 = args[2].([]model.PortMapping)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEngine_Forward_Call) Return(err error) *MockEngine_Forward_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEngine_Forward_Call) RunAndReturn(run func(ctx context.Context, id string, ports []model.PortMapping) error) *MockEngine_Forward_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockEngine
func (_mock *MockEngine) Remove(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEngine_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockEngine_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEngine_Expecter) Remove(ctx interface{}, id interface{}) *MockEngine_Remove_Call {
	return &MockEngine_Remove_Call{Call: _e.mock.On("Remove", ctx, id)}
}

func (_c *MockEngine_Remove_Call) Run(run func(ctx context.Context, id string)) *MockEngine_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEngine_Remove_Call) Return(err error) *MockEngine_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEngine_Remove_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockEngine_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockEngine
func (_mock *MockEngine) Start(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEngine_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockEngine_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEngine_Expecter) Start(ctx interface{}, id interface{}) *MockEngine_Start_Call {
	return &MockEngine_Start_Call{Call: _e.mock.On("Start", ctx, id)}
}

func (_c *MockEngine_Start_Call) Run(run func(ctx context.Context, id string)) *MockEngine_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEngine_Start_Call) Return(err error) *MockEngine_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEngine_Start_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockEngine_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockEngine
func (_mock *MockEngine) Status(ctx context.Context, id string) (*model.Sandbox, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *model.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Sandbox, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Sandbox); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sandbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEngine_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockEngine_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEngine_Expecter) Status(ctx interface{}, id interface{}) *MockEngine_Status_Call {
	return &MockEngine_Status_Call{Call: _e.mock.On("Status", ctx, id)}
}

func (_c *MockEngine_Status_Call) Run(run func(ctx context.Context, id string)) *MockEngine_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEngine_Status_Call) Return(sandbox *model.Sandbox, err error) *MockEngine_Status_Call {
	_c.Call.Return(sandbox, err)
	return _c
}

func (_c *MockEngine_Status_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Sandbox, error)) *MockEngine_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockEngine
func (_mock *MockEngine) Stop(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEngine_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockEngine_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEngine_Expecter) Stop(ctx interface{}, id interface{}) *MockEngine_Stop_Call {
	return &MockEngine_Stop_Call{Call: _e.mock.On("Stop", ctx, id)}
}

func (_c *MockEngine_Stop_Call) Run(run func(ctx context.Context, id string)) *MockEngine_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEngine_Stop_Call) Return(err error) *MockEngine_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEngine_Stop_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockEngine_Stop_Call {
	_c.Call.Return(run)
	return _c
}
