// Code generated by mockery v2.53.5. DO NOT EDIT.

package storagemock

import (
	context "context"

	model "github.com/slok/sbx/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateSandbox provides a mock function with given fields: ctx, s
func (_m *MockRepository) CreateSandbox(ctx context.Context, s model.Sandbox) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSandbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Sandbox) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSandbox'
type MockRepository_CreateSandbox_Call struct {
	*mock.Call
}

// CreateSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - s model.Sandbox
func (_e *MockRepository_Expecter) CreateSandbox(ctx interface{}, s interface{}) *MockRepository_CreateSandbox_Call {
	return &MockRepository_CreateSandbox_Call{Call: _e.mock.On("CreateSandbox", ctx, s)}
}

func (_c *MockRepository_CreateSandbox_Call) Run(run func(ctx context.Context, s model.Sandbox)) *MockRepository_CreateSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Sandbox))
	})
	return _c
}

func (_c *MockRepository_CreateSandbox_Call) Return(_a0 error) *MockRepository_CreateSandbox_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateSandbox_Call) RunAndReturn(run func(context.Context, model.Sandbox) error) *MockRepository_CreateSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSandbox provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteSandbox(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSandbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSandbox'
type MockRepository_DeleteSandbox_Call struct {
	*mock.Call
}

// DeleteSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DeleteSandbox(ctx interface{}, id interface{}) *MockRepository_DeleteSandbox_Call {
	return &MockRepository_DeleteSandbox_Call{Call: _e.mock.On("DeleteSandbox", ctx, id)}
}

func (_c *MockRepository_DeleteSandbox_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DeleteSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteSandbox_Call) Return(_a0 error) *MockRepository_DeleteSandbox_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteSandbox_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_DeleteSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetSandbox provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetSandbox(ctx context.Context, id string) (*model.Sandbox, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSandbox")
	}

	var r0 *model.Sandbox
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Sandbox, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Sandbox); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sandbox)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandbox'
type MockRepository_GetSandbox_Call struct {
	*mock.Call
}

// GetSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetSandbox(ctx interface{}, id interface{}) *MockRepository_GetSandbox_Call {
	return &MockRepository_GetSandbox_Call{Call: _e.mock.On("GetSandbox", ctx, id)}
}

func (_c *MockRepository_GetSandbox_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetSandbox_Call) Return(_a0 *model.Sandbox, _a1 error) *MockRepository_GetSandbox_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSandbox_Call) RunAndReturn(run func(context.Context, string) (*model.Sandbox, error)) *MockRepository_GetSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetSandboxByName provides a mock function with given fields: ctx, name
func (_m *MockRepository) GetSandboxByName(ctx context.Context, name string) (*model.Sandbox, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSandboxByName")
	}

	var r0 *model.Sandbox
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Sandbox, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Sandbox); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sandbox)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSandboxByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandboxByName'
type MockRepository_GetSandboxByName_Call struct {
	*mock.Call
}

// GetSandboxByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRepository_Expecter) GetSandboxByName(ctx interface{}, name interface{}) *MockRepository_GetSandboxByName_Call {
	return &MockRepository_GetSandboxByName_Call{Call: _e.mock.On("GetSandboxByName", ctx, name)}
}

func (_c *MockRepository_GetSandboxByName_Call) Run(run func(ctx context.Context, name string)) *MockRepository_GetSandboxByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetSandboxByName_Call) Return(_a0 *model.Sandbox, _a1 error) *MockRepository_GetSandboxByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSandboxByName_Call) RunAndReturn(run func(context.Context, string) (*model.Sandbox, error)) *MockRepository_GetSandboxByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListSandboxes provides a mock function with given fields: ctx
func (_m *MockRepository) ListSandboxes(ctx context.Context) ([]model.Sandbox, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSandboxes")
	}

	var r0 []model.Sandbox
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Sandbox, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Sandbox); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Sandbox)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListSandboxes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSandboxes'
type MockRepository_ListSandboxes_Call struct {
	*mock.Call
}

// ListSandboxes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListSandboxes(ctx interface{}) *MockRepository_ListSandboxes_Call {
	return &MockRepository_ListSandboxes_Call{Call: _e.mock.On("ListSandboxes", ctx)}
}

func (_c *MockRepository_ListSandboxes_Call) Run(run func(ctx context.Context)) *MockRepository_ListSandboxes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListSandboxes_Call) Return(_a0 []model.Sandbox, _a1 error) *MockRepository_ListSandboxes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListSandboxes_Call) RunAndReturn(run func(context.Context) ([]model.Sandbox, error)) *MockRepository_ListSandboxes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSandbox provides a mock function with given fields: ctx, s
func (_m *MockRepository) UpdateSandbox(ctx context.Context, s model.Sandbox) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSandbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Sandbox) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSandbox'
type MockRepository_UpdateSandbox_Call struct {
	*mock.Call
}

// UpdateSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - s model.Sandbox
func (_e *MockRepository_Expecter) UpdateSandbox(ctx interface{}, s interface{}) *MockRepository_UpdateSandbox_Call {
	return &MockRepository_UpdateSandbox_Call{Call: _e.mock.On("UpdateSandbox", ctx, s)}
}

func (_c *MockRepository_UpdateSandbox_Call) Run(run func(ctx context.Context, s model.Sandbox)) *MockRepository_UpdateSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Sandbox))
	})
	return _c
}

func (_c *MockRepository_UpdateSandbox_Call) Return(_a0 error) *MockRepository_UpdateSandbox_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateSandbox_Call) RunAndReturn(run func(context.Context, model.Sandbox) error) *MockRepository_UpdateSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
