// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storagemock

import (
	"context"

	"github.com/slok/sbx/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateSandbox provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateSandbox(ctx context.Context, s model.Sandbox) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSandbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Sandbox) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSandbox'
type MockRepository_CreateSandbox_Call struct {
	*mock.Call
}

// CreateSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - s model.Sandbox
func (_e *MockRepository_Expecter) CreateSandbox(ctx interface{}, s interface{}) *MockRepository_CreateSandbox_Call {
	return &MockRepository_CreateSandbox_Call{Call: _e.mock.On("CreateSandbox", ctx, s)}
}

func (_c *MockRepository_CreateSandbox_Call) Run(run func(ctx context.Context, s model.Sandbox)) *MockRepository_CreateSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Sandbox
		if args[1] != nil {
			arg1 = args[1].(model.Sandbox)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateSandbox_Call) Return(err error) *MockRepository_CreateSandbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateSandbox_Call) RunAndReturn(run func(ctx context.Context, s model.Sandbox) error) *MockRepository_CreateSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSnapshot provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateSnapshot(ctx context.Context, s model.Snapshot) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Snapshot) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSnapshot'
type MockRepository_CreateSnapshot_Call struct {
	*mock.Call
}

// CreateSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - s model.Snapshot
func (_e *MockRepository_Expecter) CreateSnapshot(ctx interface{}, s interface{}) *MockRepository_CreateSnapshot_Call {
	return &MockRepository_CreateSnapshot_Call{Call: _e.mock.On("CreateSnapshot", ctx, s)}
}

func (_c *MockRepository_CreateSnapshot_Call) Run(run func(ctx context.Context, s model.Snapshot)) *MockRepository_CreateSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Snapshot
		if args[1] != nil {
			arg1 = args[1].(model.Snapshot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateSnapshot_Call) Return(err error) *MockRepository_CreateSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateSnapshot_Call) RunAndReturn(run func(ctx context.Context, s model.Snapshot) error) *MockRepository_CreateSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSandbox provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteSandbox(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSandbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSandbox'
type MockRepository_DeleteSandbox_Call struct {
	*mock.Call
}

// DeleteSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DeleteSandbox(ctx interface{}, id interface{}) *MockRepository_DeleteSandbox_Call {
	return &MockRepository_DeleteSandbox_Call{Call: _e.mock.On("DeleteSandbox", ctx, id)}
}

func (_c *MockRepository_DeleteSandbox_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DeleteSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteSandbox_Call) Return(err error) *MockRepository_DeleteSandbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteSandbox_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_DeleteSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSnapshot provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteSnapshot(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSnapshot'
type MockRepository_DeleteSnapshot_Call struct {
	*mock.Call
}

// DeleteSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DeleteSnapshot(ctx interface{}, id interface{}) *MockRepository_DeleteSnapshot_Call {
	return &MockRepository_DeleteSnapshot_Call{Call: _e.mock.On("DeleteSnapshot", ctx, id)}
}

func (_c *MockRepository_DeleteSnapshot_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DeleteSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteSnapshot_Call) Return(err error) *MockRepository_DeleteSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteSnapshot_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_DeleteSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetSandbox provides a mock function for the type MockRepository
func (_mock *MockRepository) GetSandbox(ctx context.Context, id string) (*model.Sandbox, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSandbox")
	}

	var r0 *model.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Sandbox, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Sandbox); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sandbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandbox'
type MockRepository_GetSandbox_Call struct {
	*mock.Call
}

// GetSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetSandbox(ctx interface{}, id interface{}) *MockRepository_GetSandbox_Call {
	return &MockRepository_GetSandbox_Call{Call: _e.mock.On("GetSandbox", ctx, id)}
}

func (_c *MockRepository_GetSandbox_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetSandbox_Call) Return(sandbox *model.Sandbox, err error) *MockRepository_GetSandbox_Call {
	_c.Call.Return(sandbox, err)
	return _c
}

func (_c *MockRepository_GetSandbox_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Sandbox, error)) *MockRepository_GetSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetSandboxByName provides a mock function for the type MockRepository
func (_mock *MockRepository) GetSandboxByName(ctx context.Context, name string) (*model.Sandbox, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSandboxByName")
	}

	var r0 *model.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Sandbox, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Sandbox); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sandbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetSandboxByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandboxByName'
type MockRepository_GetSandboxByName_Call struct {
	*mock.Call
}

// GetSandboxByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRepository_Expecter) GetSandboxByName(ctx interface{}, name interface{}) *MockRepository_GetSandboxByName_Call {
	return &MockRepository_GetSandboxByName_Call{Call: _e.mock.On("GetSandboxByName", ctx, name)}
}

func (_c *MockRepository_GetSandboxByName_Call) Run(run func(ctx context.Context, name string)) *MockRepository_GetSandboxByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetSandboxByName_Call) Return(sandbox *model.Sandbox, err error) *MockRepository_GetSandboxByName_Call {
	_c.Call.Return(sandbox, err)
	return _c
}

func (_c *MockRepository_GetSandboxByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*model.Sandbox, error)) *MockRepository_GetSandboxByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetSnapshot provides a mock function for the type MockRepository
func (_mock *MockRepository) GetSnapshot(ctx context.Context, id string) (*model.Snapshot, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshot")
	}

	var r0 *model.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Snapshot, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Snapshot); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshot'
type MockRepository_GetSnapshot_Call struct {
	*mock.Call
}

// GetSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetSnapshot(ctx interface{}, id interface{}) *MockRepository_GetSnapshot_Call {
	return &MockRepository_GetSnapshot_Call{Call: _e.mock.On("GetSnapshot", ctx, id)}
}

func (_c *MockRepository_GetSnapshot_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetSnapshot_Call) Return(snapshot *model.Snapshot, err error) *MockRepository_GetSnapshot_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockRepository_GetSnapshot_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Snapshot, error)) *MockRepository_GetSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetSnapshotByName provides a mock function for the type MockRepository
func (_mock *MockRepository) GetSnapshotByName(ctx context.Context, name string) (*model.Snapshot, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshotByName")
	}

	var r0 *model.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Snapshot, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Snapshot); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetSnapshotByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshotByName'
type MockRepository_GetSnapshotByName_Call struct {
	*mock.Call
}

// GetSnapshotByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRepository_Expecter) GetSnapshotByName(ctx interface{}, name interface{}) *MockRepository_GetSnapshotByName_Call {
	return &MockRepository_GetSnapshotByName_Call{Call: _e.mock.On("GetSnapshotByName", ctx, name)}
}

func (_c *MockRepository_GetSnapshotByName_Call) Run(run func(ctx context.Context, name string)) *MockRepository_GetSnapshotByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetSnapshotByName_Call) Return(snapshot *model.Snapshot, err error) *MockRepository_GetSnapshotByName_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockRepository_GetSnapshotByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*model.Snapshot, error)) *MockRepository_GetSnapshotByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListSandboxes provides a mock function for the type MockRepository
func (_mock *MockRepository) ListSandboxes(ctx context.Context) ([]model.Sandbox, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSandboxes")
	}

	var r0 []model.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Sandbox, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Sandbox); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Sandbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListSandboxes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSandboxes'
type MockRepository_ListSandboxes_Call struct {
	*mock.Call
}

// ListSandboxes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListSandboxes(ctx interface{}) *MockRepository_ListSandboxes_Call {
	return &MockRepository_ListSandboxes_Call{Call: _e.mock.On("ListSandboxes", ctx)}
}

func (_c *MockRepository_ListSandboxes_Call) Run(run func(ctx context.Context)) *MockRepository_ListSandboxes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ListSandboxes_Call) Return(sandboxs []model.Sandbox, err error) *MockRepository_ListSandboxes_Call {
	_c.Call.Return(sandboxs, err)
	return _c
}

func (_c *MockRepository_ListSandboxes_Call) RunAndReturn(run func(ctx context.Context) ([]model.Sandbox, error)) *MockRepository_ListSandboxes_Call {
	_c.Call.Return(run)
	return _c
}

// ListSnapshots provides a mock function for the type MockRepository
func (_mock *MockRepository) ListSnapshots(ctx context.Context) ([]model.Snapshot, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSnapshots")
	}

	var r0 []model.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Snapshot, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Snapshot); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSnapshots'
type MockRepository_ListSnapshots_Call struct {
	*mock.Call
}

// ListSnapshots is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListSnapshots(ctx interface{}) *MockRepository_ListSnapshots_Call {
	return &MockRepository_ListSnapshots_Call{Call: _e.mock.On("ListSnapshots", ctx)}
}

func (_c *MockRepository_ListSnapshots_Call) Run(run func(ctx context.Context)) *MockRepository_ListSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ListSnapshots_Call) Return(snapshots []model.Snapshot, err error) *MockRepository_ListSnapshots_Call {
	_c.Call.Return(snapshots, err)
	return _c
}

func (_c *MockRepository_ListSnapshots_Call) RunAndReturn(run func(ctx context.Context) ([]model.Snapshot, error)) *MockRepository_ListSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSandbox provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateSandbox(ctx context.Context, s model.Sandbox) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSandbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Sandbox) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSandbox'
type MockRepository_UpdateSandbox_Call struct {
	*mock.Call
}

// UpdateSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - s model.Sandbox
func (_e *MockRepository_Expecter) UpdateSandbox(ctx interface{}, s interface{}) *MockRepository_UpdateSandbox_Call {
	return &MockRepository_UpdateSandbox_Call{Call: _e.mock.On("UpdateSandbox", ctx, s)}
}

func (_c *MockRepository_UpdateSandbox_Call) Run(run func(ctx context.Context, s model.Sandbox)) *MockRepository_UpdateSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Sandbox
		if args[1] != nil {
			arg1 = args[1].(model.Sandbox)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateSandbox_Call) Return(err error) *MockRepository_UpdateSandbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateSandbox_Call) RunAndReturn(run func(ctx context.Context, s model.Sandbox) error) *MockRepository_UpdateSandbox_Call {
	_c.Call.Return(run)
	return _c
}
