// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package imagemock

import (
	"context"

	"github.com/slok/sbx/internal/image"
	"github.com/slok/sbx/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImageManager creates a new instance of MockImageManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageManager {
	mock := &MockImageManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageManager is an autogenerated mock type for the ImageManager type
type MockImageManager struct {
	mock.Mock
}

type MockImageManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageManager) EXPECT() *MockImageManager_Expecter {
	return &MockImageManager_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type MockImageManager
func (_mock *MockImageManager) Exists(ctx context.Context, version string) (bool, error) {
	ret := _mock.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, version)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageManager_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockImageManager_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *MockImageManager_Expecter) Exists(ctx interface{}, version interface{}) *MockImageManager_Exists_Call {
	return &MockImageManager_Exists_Call{Call: _e.mock.On("Exists", ctx, version)}
}

func (_c *MockImageManager_Exists_Call) Run(run func(ctx context.Context, version string)) *MockImageManager_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageManager_Exists_Call) Return(b bool, err error) *MockImageManager_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockImageManager_Exists_Call) RunAndReturn(run func(ctx context.Context, version string) (bool, error)) *MockImageManager_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FirecrackerPath provides a mock function for the type MockImageManager
func (_mock *MockImageManager) FirecrackerPath(version string) string {
	ret := _mock.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for FirecrackerPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(version)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockImageManager_FirecrackerPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirecrackerPath'
type MockImageManager_FirecrackerPath_Call struct {
	*mock.Call
}

// FirecrackerPath is a helper method to define mock.On call
//   - version string
func (_e *MockImageManager_Expecter) FirecrackerPath(version interface{}) *MockImageManager_FirecrackerPath_Call {
	return &MockImageManager_FirecrackerPath_Call{Call: _e.mock.On("FirecrackerPath", version)}
}

func (_c *MockImageManager_FirecrackerPath_Call) Run(run func(version string)) *MockImageManager_FirecrackerPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageManager_FirecrackerPath_Call) Return(s string) *MockImageManager_FirecrackerPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockImageManager_FirecrackerPath_Call) RunAndReturn(run func(version string) string) *MockImageManager_FirecrackerPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetManifest provides a mock function for the type MockImageManager
func (_mock *MockImageManager) GetManifest(ctx context.Context, version string) (*model.ImageManifest, error) {
	ret := _mock.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for GetManifest")
	}

	var r0 *model.ImageManifest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ImageManifest, error)); ok {
		return returnFunc(ctx, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ImageManifest); ok {
		r0 = returnFunc(ctx, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ImageManifest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageManager_GetManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManifest'
type MockImageManager_GetManifest_Call struct {
	*mock.Call
}

// GetManifest is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *MockImageManager_Expecter) GetManifest(ctx interface{}, version interface{}) *MockImageManager_GetManifest_Call {
	return &MockImageManager_GetManifest_Call{Call: _e.mock.On("GetManifest", ctx, version)}
}

func (_c *MockImageManager_GetManifest_Call) Run(run func(ctx context.Context, version string)) *MockImageManager_GetManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageManager_GetManifest_Call) Return(imageManifest *model.ImageManifest, err error) *MockImageManager_GetManifest_Call {
	_c.Call.Return(imageManifest, err)
	return _c
}

func (_c *MockImageManager_GetManifest_Call) RunAndReturn(run func(ctx context.Context, version string) (*model.ImageManifest, error)) *MockImageManager_GetManifest_Call {
	_c.Call.Return(run)
	return _c
}

// KernelPath provides a mock function for the type MockImageManager
func (_mock *MockImageManager) KernelPath(version string) string {
	ret := _mock.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for KernelPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(version)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockImageManager_KernelPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KernelPath'
type MockImageManager_KernelPath_Call struct {
	*mock.Call
}

// KernelPath is a helper method to define mock.On call
//   - version string
func (_e *MockImageManager_Expecter) KernelPath(version interface{}) *MockImageManager_KernelPath_Call {
	return &MockImageManager_KernelPath_Call{Call: _e.mock.On("KernelPath", version)}
}

func (_c *MockImageManager_KernelPath_Call) Run(run func(version string)) *MockImageManager_KernelPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageManager_KernelPath_Call) Return(s string) *MockImageManager_KernelPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockImageManager_KernelPath_Call) RunAndReturn(run func(version string) string) *MockImageManager_KernelPath_Call {
	_c.Call.Return(run)
	return _c
}

// ListReleases provides a mock function for the type MockImageManager
func (_mock *MockImageManager) ListReleases(ctx context.Context) ([]model.ImageRelease, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListReleases")
	}

	var r0 []model.ImageRelease
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.ImageRelease, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.ImageRelease); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ImageRelease)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageManager_ListReleases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReleases'
type MockImageManager_ListReleases_Call struct {
	*mock.Call
}

// ListReleases is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImageManager_Expecter) ListReleases(ctx interface{}) *MockImageManager_ListReleases_Call {
	return &MockImageManager_ListReleases_Call{Call: _e.mock.On("ListReleases", ctx)}
}

func (_c *MockImageManager_ListReleases_Call) Run(run func(ctx context.Context)) *MockImageManager_ListReleases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageManager_ListReleases_Call) Return(imageReleases []model.ImageRelease, err error) *MockImageManager_ListReleases_Call {
	_c.Call.Return(imageReleases, err)
	return _c
}

func (_c *MockImageManager_ListReleases_Call) RunAndReturn(run func(ctx context.Context) ([]model.ImageRelease, error)) *MockImageManager_ListReleases_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function for the type MockImageManager
func (_mock *MockImageManager) Pull(ctx context.Context, version string, opts image.PullOptions) (*image.PullResult, error) {
	ret := _mock.Called(ctx, version, opts)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 *image.PullResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, image.PullOptions) (*image.PullResult, error)); ok {
		return returnFunc(ctx, version, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, image.PullOptions) *image.PullResult); ok {
		r0 = returnFunc(ctx, version, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.PullResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, image.PullOptions) error); ok {
		r1 = returnFunc(ctx, version, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageManager_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockImageManager_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
//   - opts image.PullOptions
func (_e *MockImageManager_Expecter) Pull(ctx interface{}, version interface{}, opts interface{}) *MockImageManager_Pull_Call {
	return &MockImageManager_Pull_Call{Call: _e.mock.On("Pull", ctx, version, opts)}
}

func (_c *MockImageManager_Pull_Call) Run(run func(ctx context.Context, version string, opts image.PullOptions)) *MockImageManager_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 image.PullOptions
		if args[2] != nil {
			arg2 = args[2].(image.PullOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageManager_Pull_Call) Return(pullResult *image.PullResult, err error) *MockImageManager_Pull_Call {
	_c.Call.Return(pullResult, err)
	return _c
}

func (_c *MockImageManager_Pull_Call) RunAndReturn(run func(ctx context.Context, version string, opts image.PullOptions) (*image.PullResult, error)) *MockImageManager_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockImageManager
func (_mock *MockImageManager) Remove(ctx context.Context, version string) error {
	ret := _mock.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, version)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageManager_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockImageManager_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *MockImageManager_Expecter) Remove(ctx interface{}, version interface{}) *MockImageManager_Remove_Call {
	return &MockImageManager_Remove_Call{Call: _e.mock.On("Remove", ctx, version)}
}

func (_c *MockImageManager_Remove_Call) Run(run func(ctx context.Context, version string)) *MockImageManager_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageManager_Remove_Call) Return(err error) *MockImageManager_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageManager_Remove_Call) RunAndReturn(run func(ctx context.Context, version string) error) *MockImageManager_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RootFSPath provides a mock function for the type MockImageManager
func (_mock *MockImageManager) RootFSPath(version string) string {
	ret := _mock.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for RootFSPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(version)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockImageManager_RootFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootFSPath'
type MockImageManager_RootFSPath_Call struct {
	*mock.Call
}

// RootFSPath is a helper method to define mock.On call
//   - version string
func (_e *MockImageManager_Expecter) RootFSPath(version interface{}) *MockImageManager_RootFSPath_Call {
	return &MockImageManager_RootFSPath_Call{Call: _e.mock.On("RootFSPath", version)}
}

func (_c *MockImageManager_RootFSPath_Call) Run(run func(version string)) *MockImageManager_RootFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageManager_RootFSPath_Call) Return(s string) *MockImageManager_RootFSPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockImageManager_RootFSPath_Call) RunAndReturn(run func(version string) string) *MockImageManager_RootFSPath_Call {
	_c.Call.Return(run)
	return _c
}
